# Generated by Django 4.2.5 on 2023-09-27 15:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('is_correct', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ModOneUserQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question_quantity', models.IntegerField(default=0)),
                ('quiz_start_time', models.DateTimeField(blank=True, null=True)),
                ('quiz_end_time', models.DateTimeField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField()),
                ('question_type', models.CharField(choices=[('Single Choice Question', 'Single Choice Question'), ('Multiple Select Question', 'Multiple Select Question')], max_length=50)),
                ('marks', models.IntegerField(default=1)),
                ('time_limit', models.IntegerField(default=90)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('Semesters', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_questions', to='modone.semester')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ModUserResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question_type', models.CharField(blank=True, choices=[('Single Choice Question', 'Single Choice Question'), ('Multiple Select Question', 'Multiple Select Question')], max_length=50, null=True)),
                ('marks', models.FloatField(default=0.0)),
                ('is_correct', models.BooleanField(default=False)),
                ('multi_selected_choices', models.ManyToManyField(blank=True, related_name='user_response_multi_selected_choices', to='modone.choice')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modone.question')),
                ('single_selected_choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_response_quiz_single_selected_choice', to='modone.choice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_quiz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_response_user_quiz', to='modone.modoneuserquiz')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='modoneuserquiz',
            name='question',
            field=models.ManyToManyField(blank=True, related_name='user_quiz_question', to='modone.question'),
        ),
        migrations.AddField(
            model_name='modoneuserquiz',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_quiz_semester', to='modone.semester'),
        ),
        migrations.AddField(
            model_name='modoneuserquiz',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='modone.question'),
        ),
    ]
